# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1139, 658)
        self.labelTitle = QtWidgets.QLabel(Dialog)
        self.labelTitle.setGeometry(QtCore.QRect(20, 20, 1101, 20))
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.labelAverageOfDays = QtWidgets.QLabel(Dialog)
        self.labelAverageOfDays.setGeometry(QtCore.QRect(710, 400, 131, 16))
        self.labelAverageOfDays.setObjectName("labelAverageOfDays")
        self.groupBoxOption = QtWidgets.QGroupBox(Dialog)
        self.groupBoxOption.setGeometry(QtCore.QRect(880, 480, 131, 121))
        self.groupBoxOption.setObjectName("groupBoxOption")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBoxOption)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 111, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonCumulative = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonCumulative.setChecked(True)
        self.radioButtonCumulative.setObjectName("radioButtonCumulative")
        self.verticalLayout.addWidget(self.radioButtonCumulative)
        self.radioButtonDaily = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonDaily.setObjectName("radioButtonDaily")
        self.verticalLayout.addWidget(self.radioButtonDaily)
        self.groupBoxDataToPlot = QtWidgets.QGroupBox(Dialog)
        self.groupBoxDataToPlot.setGeometry(QtCore.QRect(710, 480, 101, 121))
        self.groupBoxDataToPlot.setObjectName("groupBoxDataToPlot")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxDataToPlot)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 81, 83))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButtonCases = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButtonCases.setChecked(True)
        self.radioButtonCases.setObjectName("radioButtonCases")
        self.verticalLayout_2.addWidget(self.radioButtonCases)
        self.radioButtonDeaths = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButtonDeaths.setObjectName("radioButtonDeaths")
        self.verticalLayout_2.addWidget(self.radioButtonDeaths)
        self.radioButtonBoth = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButtonBoth.setObjectName("radioButtonBoth")
        self.verticalLayout_2.addWidget(self.radioButtonBoth)
        self.labelCountry = QtWidgets.QLabel(Dialog)
        self.labelCountry.setGeometry(QtCore.QRect(20, 410, 59, 16))
        self.labelCountry.setObjectName("labelCountry")
        self.comboBoxCountries = QtWidgets.QComboBox(Dialog)
        self.comboBoxCountries.setGeometry(QtCore.QRect(20, 440, 321, 25))
        self.comboBoxCountries.setObjectName("comboBoxCountries")
        self.labelStateOfRegion = QtWidgets.QLabel(Dialog)
        self.labelStateOfRegion.setGeometry(QtCore.QRect(360, 410, 106, 16))
        self.labelStateOfRegion.setObjectName("labelStateOfRegion")
        self.comboBoxRegions = QtWidgets.QComboBox(Dialog)
        self.comboBoxRegions.setGeometry(QtCore.QRect(360, 440, 321, 25))
        self.comboBoxRegions.setObjectName("comboBoxRegions")
        self.sliderAverage = QtWidgets.QSlider(Dialog)
        self.sliderAverage.setGeometry(QtCore.QRect(710, 440, 381, 20))
        self.sliderAverage.setMinimum(1)
        self.sliderAverage.setMaximum(15)
        self.sliderAverage.setOrientation(QtCore.Qt.Horizontal)
        self.sliderAverage.setObjectName("sliderAverage")
        self.mplwidget = MplWidget(Dialog)
        self.mplwidget.setGeometry(QtCore.QRect(20, 50, 1091, 331))
        self.mplwidget.setObjectName("mplwidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "COVID-19 Data Visualization (Data source: Jhons Hopkins University)"))
        self.labelTitle.setText(_translate("Dialog", "Dayly Number of Cases and Deaths in "))
        self.labelAverageOfDays.setText(_translate("Dialog", "Averaged 1 of day"))
        self.groupBoxOption.setTitle(_translate("Dialog", "Option"))
        self.radioButtonCumulative.setText(_translate("Dialog", "Cumulative"))
        self.radioButtonDaily.setText(_translate("Dialog", "Daily"))
        self.groupBoxDataToPlot.setTitle(_translate("Dialog", "Data to Plot"))
        self.radioButtonCases.setText(_translate("Dialog", "Cases"))
        self.radioButtonDeaths.setText(_translate("Dialog", "Deaths"))
        self.radioButtonBoth.setText(_translate("Dialog", "Both"))
        self.labelCountry.setText(_translate("Dialog", "Country:"))
        self.labelStateOfRegion.setText(_translate("Dialog", "State of Region"))
from mplwidget import MplWidget
