# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(491, 334)
        self.line_edit_expression = QtWidgets.QLineEdit(Dialog)
        self.line_edit_expression.setGeometry(QtCore.QRect(110, 60, 311, 20))
        self.line_edit_expression.setObjectName("line_edit_expression")
        self.line_edit_result = QtWidgets.QLineEdit(Dialog)
        self.line_edit_result.setGeometry(QtCore.QRect(110, 180, 113, 20))
        self.line_edit_result.setObjectName("line_edit_result")
        self.label_result = QtWidgets.QLabel(Dialog)
        self.label_result.setGeometry(QtCore.QRect(50, 180, 47, 21))
        self.label_result.setObjectName("label_result")
        self.label_expression = QtWidgets.QLabel(Dialog)
        self.label_expression.setGeometry(QtCore.QRect(30, 60, 81, 16))
        self.label_expression.setObjectName("label_expression")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(120, 90, 301, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Expression Analizer"))
        self.label_result.setText(_translate("Dialog", "Result"))
        self.label_expression.setText(_translate("Dialog", "Expression: X="))
        self.label_3.setText(_translate("Dialog", "Correct: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
