# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(914, 236)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 60, 121, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(680, 60, 111, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(360, 60, 221, 151))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 19, 221, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonMeters2Centimeters = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonMeters2Centimeters.setObjectName("radioButtonMeters2Centimeters")
        self.verticalLayout.addWidget(self.radioButtonMeters2Centimeters)
        self.radioButtonCelcius2Farenheit = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonCelcius2Farenheit.setObjectName("radioButtonCelcius2Farenheit")
        self.verticalLayout.addWidget(self.radioButtonCelcius2Farenheit)
        self.lineEditInput = QtWidgets.QLineEdit(Dialog)
        self.lineEditInput.setGeometry(QtCore.QRect(80, 100, 113, 25))
        self.lineEditInput.setObjectName("lineEditInput")
        self.lineEditOutput = QtWidgets.QLineEdit(Dialog)
        self.lineEditOutput.setGeometry(QtCore.QRect(680, 90, 113, 25))
        self.lineEditOutput.setObjectName("lineEditOutput")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Datos de entrada"))
        self.label_3.setText(_translate("Dialog", "Datos de salida"))
        self.groupBox.setTitle(_translate("Dialog", "Opciones"))
        self.radioButtonMeters2Centimeters.setText(_translate("Dialog", "Metors a centimetors"))
        self.radioButtonCelcius2Farenheit.setText(_translate("Dialog", "Celcius a Farenheit"))
